name: appchat
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.16.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  firebase_storage: ^11.7.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/